src/stream.ts
src/transport.ts

Add mute/unmute

---

src/Client.ts
src/index.ts
src/proto.ts
src/stream.ts

Requires passing tracks info into subscribe. This is used in screen shares where only video is sent.

Only add transceiver for known tracks

---

src/stream.ts

This adds 2560x1440 QHD resolution for screenshare purposes. Also, fix a typo with FHD width resolution.

Fix FHD resolution, add QHD resolution

---

.github/workflows/publish.yaml

fix(ci): npm version package.json

---

src/peerconnection.ts

fix(pc): initialize transceivers

---

src/stream.ts

feat(localstream): unpublish

---

src/signal/ion-sfu.ts

Bubble up websocket error to IonSFUJSONRPCSignal

---

src/client.ts

Fix polite peer

---

src/client.ts

fix(signal): improve polite peer

---

src/stream.ts

fix(stream): unpublish own tracks

---

src/client.ts
src/stream.ts

feat: sender streams

---

package-lock.json
src/client.ts
src/stream.ts

fix: make local

---

src/client.ts

This PR will allow select codecs using tranceivers api.

feat(client): select codecs

---

src/signal/ion-sfu.ts

Add onclose handler to jsonrpc signaler

---

src/stream.ts

This PR will allow to reuse local transceivers.

feat(stream): reuse transceivers

---

src/client.ts
src/signal/index.ts
src/signal/ion-sfu.ts
src/stream.ts

feat: pub sub pc

---

src/stream.ts

feat: default simulcast encodings

---

README.md
src/client.ts
src/stream.ts

feat: datachannel support

---

src/signal/ion-sfu.ts

- Check errors and reject
- Remove offer handler inside if(resp.id) block

Fix Signal Promises

---

src/stream.ts

This was breaking audio device switching

ComputeAudioConstraints

---

README.md
src/signal/json-rpc-impl.ts
src/stream.ts
yarn.lock

- make jsonrpc2 call/notify generic 
- update readme for how to import jsonrpc2signaler
- always remove previous track when updating track (mic switching while muted was accumulating tracks)

Implement a generic jsonrpc2 call/notify function; fix issue with mic switching while muted

---

src/stream.ts

* This gives us the option to manipulate bitrate and framerate to respond to network conditions, without the need to restart the stream.
Fixes #...

Add option to update media encoding params for local streams

---

src/client.ts
src/stream.ts

Add temporal and speaker events support

Add temporal layer change

---

src/stream.ts

Add dummy tracks for mute, this will allow other service whose depend on correct TS sequence

feat: Add dummy tracks for muting

---

src/stream.ts

Fix empty tracks to send silent packets

fix: empty tracks to send silent packets

---

decs.d.ts
src/stream.ts

Add support for choosing preferred video codec profile

---

src/client.ts

Previously, the (implicit) promise returned by `join` would resolve
after establishing the transports, but before the API data channel was
attached.  This meant there was a small window of time where the API
data channel was not ready, and trying to use the subscriber API during
that time would fail silently.
This change returns a promise that does not resolve until after the API
channel is established.

Resolve `join` promise after API channel ready

---

src/client.ts

Revert "Resolve `join` promise after API channel ready"

---

src/signal/json-rpc-impl.ts

[jsonrpc] Support Notification Handlers 
